### ISSUE TITLE
Android P crash: reflections are not allowed anymore

### ISSUE THREAD

**Issue by courville** [archos-sa/aos-AVP#5]
AVP crashes at launch with Android P developper preview Android studio AVD image.
Logs shows dark greylist reflections (storagemanager etc.):

`
04-30 11:16:54.780 4573-4573/com.archos.mediacenter.videocommunity W/zygote: Unexpected CPU variant for X86 using defaults: x86
04-30 11:16:54.797 4573-4573/com.archos.mediacenter.videocommunity I/MultiDex: VM with version 2.1.0 has multidex support
04-30 11:16:54.798 4573-4573/com.archos.mediacenter.videocommunity I/MultiDex: Installing application
    VM has multidex support, MultiDex support library is disabled.
04-30 11:16:54.832 4573-4573/com.archos.mediacenter.videocommunity D/NetworkSecurityConfig: No Network Security Config specified, using platform default
04-30 11:16:54.833 4573-4573/com.archos.mediacenter.videocommunity W/zygote: Accessing hidden method Ldalvik/system/CloseGuard;->get()Ldalvik/system/CloseGuard; (light greylist, reflection)
04-30 11:16:54.834 4573-4573/com.archos.mediacenter.videocommunity W/zygote: Accessing hidden method Ldalvik/system/CloseGuard;->open(Ljava/lang/String;)V (light greylist, reflection)
    Accessing hidden method Ldalvik/system/CloseGuard;->warnIfOpen()V (light greylist, reflection)
04-30 11:16:54.849 4573-4573/com.archos.mediacenter.videocommunity I/MemoryIntArray: created from parcel MemoryIntArray@8649758 mMemoryAddr=3966943232 mFd=43
04-30 11:16:54.865 4573-4573/com.archos.mediacenter.videocommunity I/SQLiteCompatibilityWalFlags: Read compatibility WAL flags: compatibility_wal_supported=true, wal_syncmode=FULL
04-30 11:16:54.871 4573-4573/com.archos.mediacenter.videocommunity D/SambaConfiguration: Updating credentials cache
04-30 11:16:54.880 4573-4592/com.archos.mediacenter.videocommunity V/LibAvos: Can't load library: java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.archos.mediacenter.videocommunity-IcmplzD8db7I6BQ3qljlLQ==/base.apk"],nativeLibraryDirectories=[/data/app/com.archos.mediacenter.videocommunity-IcmplzD8db7I6BQ3qljlLQ==/lib/x86, /data/app/com.archos.mediacenter.videocommunity-IcmplzD8db7I6BQ3qljlLQ==/base.apk!/lib/x86, /system/lib]]] couldn't find "libcryptocompat.so"
    Can't load library: java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.archos.mediacenter.videocommunity-IcmplzD8db7I6BQ3qljlLQ==/base.apk"],nativeLibraryDirectories=[/data/app/com.archos.mediacenter.videocommunity-IcmplzD8db7I6BQ3qljlLQ==/lib/x86, /data/app/com.archos.mediacenter.videocommunity-IcmplzD8db7I6BQ3qljlLQ==/base.apk!/lib/x86, /system/lib]]] couldn't find "libsslcompat.so"
    Can't load library: java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.archos.mediacenter.videocommunity-IcmplzD8db7I6BQ3qljlLQ==/base.apk"],nativeLibraryDirectories=[/data/app/com.archos.mediacenter.videocommunity-IcmplzD8db7I6BQ3qljlLQ==/lib/x86, /data/app/com.archos.mediacenter.videocommunity-IcmplzD8db7I6BQ3qljlLQ==/base.apk!/lib/x86, /system/lib]]] couldn't find "libcurl.so"
04-30 11:16:54.899 4573-4592/com.archos.mediacenter.videocommunity V/libavos: libavos_acquire
04-30 11:16:54.901 4573-4592/com.archos.mediacenter.videocommunity V/libavos: libavos_debug_acquire: first init
04-30 11:16:54.902 4573-4573/com.archos.mediacenter.videocommunity D/ccl_BaseCastManager: [v2.9.1] BaseCastManager is instantiated
    Version: 2.9.1
    Application ID: 08FEA4DD
04-30 11:16:54.907 4573-4573/com.archos.mediacenter.videocommunity V/MediaRouter: Adding route: RouteInfo{ name=Phone, description=null, status=null, category=RouteCategory{ name=System types=ROUTE_TYPE_LIVE_AUDIO ROUTE_TYPE_LIVE_VIDEO  groupable=false }, supportedTypes=ROUTE_TYPE_LIVE_AUDIO ROUTE_TYPE_LIVE_VIDEO , presentationDisplay=null }
04-30 11:16:54.909 4573-4573/com.archos.mediacenter.videocommunity V/MediaRouter: Selecting route: RouteInfo{ name=Phone, description=null, status=null, category=RouteCategory{ name=System types=ROUTE_TYPE_LIVE_AUDIO ROUTE_TYPE_LIVE_VIDEO  groupable=false }, supportedTypes=ROUTE_TYPE_LIVE_AUDIO ROUTE_TYPE_LIVE_VIDEO , presentationDisplay=null }
04-30 11:16:54.911 4573-4573/com.archos.mediacenter.videocommunity I/MediaRouter: Found default route: MediaRouter.RouteInfo{ uniqueId=android/.support.v7.media.SystemMediaRouteProvider:DEFAULT_ROUTE, name=Phone, description=null, iconUri=null, enabled=true, connecting=false, connectionState=0, canDisconnect=false, playbackType=0, playbackStream=3, deviceType=0, volumeHandling=1, volume=5, volumeMax=15, presentationDisplayId=-1, extras=null, settingsIntent=null, providerPackageName=android }
04-30 11:16:54.912 4573-4573/com.archos.mediacenter.videocommunity D/ccl_VideoCastManager: [v2.9.1] VideoCastManager is instantiated
04-30 11:16:54.916 4573-4573/com.archos.mediacenter.videocommunity D/ccl_VideoCastManager: [v2.9.1] Successfully added the new MiniController com.archos.mediacenter.video.player.cast.ArchosVideoCastManager@c2fa682
    [v2.9.1] Stopped TrickPlay Timer
    [v2.9.1] Restarted Progress Timer
04-30 11:16:54.916 4573-4573/com.archos.mediacenter.videocommunity D/ccl_BaseCastManager: [v2.9.1] Successfully added the new BaseCastConsumer listener com.archos.mediacenter.video.player.cast.ArchosVideoCastManager$1@fd595d0
04-30 11:16:54.916 4573-4573/com.archos.mediacenter.videocommunity D/ccl_VideoCastManager: [v2.9.1] Successfully added the new CastConsumer listener com.archos.mediacenter.video.player.cast.ArchosVideoCastManager$1@fd595d0
04-30 11:16:54.916 4573-4573/com.archos.mediacenter.videocommunity D/AutoScrapeService: AutoScrapeService() com.archos.mediascraper.AutoScrapeService@c35a8ce
    onCreate() com.archos.mediascraper.AutoScrapeService@c35a8ce
04-30 11:16:54.917 4573-4573/com.archos.mediacenter.videocommunity D/AutoScrapeService: onStart() com.archos.mediascraper.AutoScrapeService@c35a8ce
    startScraping true
04-30 11:16:54.917 4573-4602/com.archos.mediacenter.videocommunity D/AutoScrapeService: startThread false
04-30 11:16:54.929 4573-4602/com.archos.mediacenter.videocommunity W/zygote: Accessing hidden method Landroid/database/sqlite/SQLiteDatabase;->addCustomFunction(Ljava/lang/String;ILandroid/database/sqlite/SQLiteDatabase$CustomFunction;)V (dark greylist, reflection)
04-30 11:16:54.932 4573-4602/com.archos.mediacenter.videocommunity D/AutoScrapeService: starting thread 0
04-30 11:16:54.942 4573-4573/com.archos.mediacenter.videocommunity I/zygote: The ClassLoaderContext is a special shared library.
04-30 11:16:54.943 4573-4573/com.archos.mediacenter.videocommunity W/zygote: Accessing hidden method Landroid/os/storage/StorageManager;->registerListener(Landroid/os/storage/StorageEventListener;)V (dark greylist, reflection)
04-30 11:16:54.944 4573-4573/com.archos.mediacenter.videocommunity W/zygote: Accessing hidden method Landroid/os/ServiceManager;->getService(Ljava/lang/String;)Landroid/os/IBinder; (light greylist, reflection)
    Accessing hidden method Landroid/os/storage/IStorageManager$Stub;->asInterface(Landroid/os/IBinder;)Landroid/os/storage/IStorageManager; (light greylist, reflection)
    Accessing hidden method Landroid/os/storage/StorageVolume;->getPath()Ljava/lang/String; (light greylist, reflection)
    Accessing hidden method Landroid/os/storage/VolumeInfo;->getFsUuid()Ljava/lang/String; (light greylist, reflection)
    Accessing hidden method Landroid/os/storage/VolumeInfo;->isMountedReadable()Z (dark greylist, reflection)
    Accessing hidden method Landroid/os/storage/VolumeInfo;->getDisk()Landroid/os/storage/DiskInfo; (light greylist, reflection)
    Accessing hidden method Landroid/os/storage/VolumeInfo;->getPath()Ljava/io/File; (light greylist, reflection)
    Accessing hidden method Landroid/os/storage/DiskInfo;->isSd()Z (dark greylist, reflection)
    Accessing hidden method Landroid/os/storage/DiskInfo;->isUsb()Z (dark greylist, reflection)
    Accessing hidden field Landroid/os/storage/VolumeInfo;->type:I (dark greylist, reflection)
04-30 11:16:54.946 4573-4573/com.archos.mediacenter.videocommunity W/zygote: Accessing hidden method Landroid/os/storage/IStorageManager;->getVolumes(I)[Landroid/os/storage/VolumeInfo; (dark greylist, reflection)
04-30 11:16:54.951 4573-4573/com.archos.mediacenter.videocommunity V/MediaRouter: Selecting route: RouteInfo{ name=Phone, description=null, status=null, category=RouteCategory{ name=System types=ROUTE_TYPE_LIVE_AUDIO ROUTE_TYPE_LIVE_VIDEO  groupable=false }, supportedTypes=ROUTE_TYPE_LIVE_AUDIO ROUTE_TYPE_LIVE_VIDEO , presentationDisplay=null }
04-30 11:16:54.953 4573-4573/com.archos.mediacenter.videocommunity D/AutoScrapeService: onDestroy() com.archos.mediascraper.AutoScrapeService@c35a8ce
04-30 11:16:54.967 4573-4598/com.archos.mediacenter.videocommunity D/avos_player: libavos_init
    device_config.has_hdd     0
    device_config.has_dsp     1
    device_config.has_dsp_od  1
    device_config.zone        0
    device_config.has_archos_enhancement 0
    device_config.hw_type     unknown
    device_config.cpu_count   2
    dlhelper_dlsym: dlhelper_dlsym failed: undefined symbol: _ZN7android11AudioSystem16getOutputLatencyEPj19audio_stream_type_t
    dlhelper_as_init: sym_init: dlsym failed: getOutputLatency
    audio_interface_init: opensles success
    creating mainloop (for debug only)
04-30 11:16:55.994 4573-4603/com.archos.mediacenter.videocommunity E/AndroidRuntime: FATAL EXCEPTION: ImportWorker
    Process: com.archos.mediacenter.videocommunity, PID: 4573
    android.database.sqlite.SQLiteException: no such column: storage_id (code 1 SQLITE_ERROR): , while compiling: SELECT _id, _data, _display_name, _size, date_added, date_modified, bucket_id, bucket_display_name, format, parent, storage_id FROM files WHERE (storage_id & 1 AND _data NOT NULL AND _data != '') ORDER BY _id
        at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:179)
        at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:135)
        at android.content.ContentProviderProxy.query(ContentProviderNative.java:418)
        at android.content.ContentResolver.query(ContentResolver.java:773)
        at android.content.ContentResolver.query(ContentResolver.java:723)
        at android.content.ContentResolver.query(ContentResolver.java:681)
        at com.archos.mediaprovider.video.VideoStoreImportImpl.copyData(VideoStoreImportImpl.java:453)
        at com.archos.mediaprovider.video.VideoStoreImportImpl.doFullImport(VideoStoreImportImpl.java:86)
        at com.archos.mediaprovider.video.VideoStoreImportService.doImport(VideoStoreImportService.java:310)
        at com.archos.mediaprovider.video.VideoStoreImportService.handleMessage(VideoStoreImportService.java:262)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:164)
        at android.os.HandlerThread.run(HandlerThread.java:65)
`

**Comment by jtnoronha** [comment]
I am witnessing the same problem on my Android phone. Could you point me to a solution?

**Comment by courville** [comment]
@jtnoronha oops ok your issue is on Archos Video Player. It has been fixed on Nova video player, the open source fork of Archos.
